In [104]:
import numpy as np

In [105]:
an_array=np.array([3,33,45])
print(type(an_array))

<class 'numpy.ndarray'>


In [106]:
an_array

array([ 3, 33, 45])

In [107]:
an_array2=np.array([[4,56,6],[23,44,5]])
print(type(an_array2))

<class 'numpy.ndarray'>


In [108]:
print(an_array2)

[[ 4 56  6]
 [23 44  5]]


In [109]:
an_array.shape

(3,)

In [110]:
an_array2.shape

(2, 3)

In [111]:
#access 1D array by using index 
print(an_array[0],an_array[1],an_array[2])

3 33 45


In [112]:
an_array[0]='888'


In [113]:
an_array         #ndarry are mutable , here we can change element of the arrray

array([888,  33,  45])

# how to create rank 2 array

A rank 2 ndarray is one with two dimensions. Notice the format below of [ [row] , [row] ]. 
2 dimensional arrays are great for representing matrices which are often useful in data science.

In [114]:
another=np.array([[11,235,53],[87,576,45]])
print("the 2d array \n",another,another.shape)

the 2d array 
 [[ 11 235  53]
 [ 87 576  45]] (2, 3)


In [115]:
print("Accessing elements [0,0], [0,1], and [1,0] of the ndarray: ",another[0, 0], ", ",another[0, 1],", ", another[1, 0])

Accessing elements [0,0], [0,1], and [1,0] of the ndarray:  11 ,  235 ,  87


# There are many way to create numpy arrays:

In [116]:
ex1=np.zeros((2,2))
print(ex1)      # it creates 2*2 array

[[0. 0.]
 [0. 0.]]


In [117]:
# create a 2x2 array filled with 9.0

ex2=np.full((2,2),(9.0))
print(ex2)


[[9. 9.]
 [9. 9.]]


In [118]:
# all digonal elemments are unit rest are 0
ex3=np.eye(5,5)
print(ex3)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [119]:
#create an array of ones
ex4=np.ones((2,2))
print(ex4)

[[1. 1.]
 [1. 1.]]


In [120]:
# notice that the above ndarray (ex4) is actually rank 2, it is a 2x1 array
print(ex4.shape)


# which means we need to use two indexes to access an element
print()
print(ex4[0,0])


(2, 2)

1.0


In [121]:
# create random array of random flots between 0 and 1

ex5=np.random.random((5,5))
print(ex5)

[[0.66461359 0.96333091 0.57873128 0.0924857  0.28758028]
 [0.9277299  0.09929717 0.49690815 0.26318176 0.44371812]
 [0.7950563  0.96491796 0.11004384 0.2156923  0.01355135]
 [0.01180938 0.58133984 0.52951318 0.2425228  0.06041461]
 [0.51056069 0.18802474 0.88352029 0.41871437 0.82900794]]


In [122]:
ex5.sort()
print(ex5)

[[0.0924857  0.28758028 0.57873128 0.66461359 0.96333091]
 [0.09929717 0.26318176 0.44371812 0.49690815 0.9277299 ]
 [0.01355135 0.11004384 0.2156923  0.7950563  0.96491796]
 [0.01180938 0.06041461 0.2425228  0.52951318 0.58133984]
 [0.18802474 0.41871437 0.51056069 0.82900794 0.88352029]]


# slice indexing

In [123]:
import numpy as np

# Rank 2 array of shape (3, 4)
an_array = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
print(an_array)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


Use array slicing to get a subarray consisting of the first 2 rows x 2 column

In [124]:
a_slice = an_array[0:2, 1:3]
#select 0 and 1 rows, 1 and 2 column
print(a_slice)

[[12 13]
 [22 23]]


In [125]:

print("Before:", an_array[0, 1])   #inspect the element at 0, 1  
a_slice[0, 0] = 1000    # a_slice[0, 0] is the same piece of data as an_array[0, 1]
print("After:", an_array[0, 1])
print(an_array)

Before: 12
After: 1000
[[  11 1000   13   14]
 [  21   22   23   24]
 [  31   32   33   34]]



# Use both integer indexing & slice indexing

In [126]:
an_array=np.array([[11,12,13,14],[21,22,23,24],[31,32,33,34]])  # create rank 2 array of shape 3x4
print(an_array)


[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


In [127]:
# Using both integer indexing & slicing generates an array of lower rank
low_rank=an_array[1,:]
print(low_rank,low_rank.shape)

[21 22 23 24] (4,)


In [128]:
# Slicing alone: generates an array of the same rank as the an_array
low_rank2=an_array[1:2,:]
print(low_rank2,low_rank2.shape)

#notice: [[]]

[[21 22 23 24]] (1, 4)


In [129]:
#We can do the same thing for columns of an array:
low_rank3=an_array[:,3]
print(low_rank3, low_rank3.shape)

[14 24 34] (3,)


In [130]:
low_rankcolumn=an_array[:,3]
print(low_rankcolumn, low_rankcolumn.shape)

print()
low_rankcolumn2=an_array[:,3:]
print(low_rankcolumn2, low_rankcolumn2.shape)


[14 24 34] (3,)

[[14]
 [24]
 [34]] (3, 1)


# Array Indexing for changing elements:

In [131]:
# create a new array

an_array=np.array([[11,12,13],[21,22,23],[31,32,33],[41,42,43]])
print("original array")
print(an_array)

original array
[[11 12 13]
 [21 22 23]
 [31 32 33]
 [41 42 43]]


In [132]:
# create an array of indices

col_indices=np.array([0,1,2,0])
print("\n col indices picked", col_indices)
row_indices=np.arange(4)
print('\n row indices picked', row_indices)


 col indices picked [0 1 2 0]

 row indices picked [0 1 2 3]


In [133]:
# now llets pair row indices and col indices
for i,j in zip(row_indices,col_indices):
    print(i,",",j)
    
'''for i in row indices:
    j in col indices'''

0 , 0
1 , 1
2 , 2
3 , 0


'for i in row indices:\n    j in col indices'

In [134]:
#select one element from each row

print("values in an array at this indices",an_array[row_indices,col_indices])

values in an array at this indices [11 22 33 41]


In [135]:
# now change an element from each indices that we selected
an_array[row_indices,col_indices]+=1000

In [136]:
an_array

array([[1011,   12,   13],
       [  21, 1022,   23],
       [  31,   32, 1033],
       [1041,   42,   43]])




# Boolean Indexing










Arrray indexing for changing element

create 3x2 array

In [137]:
an_array=np.array([[22,23],[34,53],[34,53]])
print(an_array)

[[22 23]
 [34 53]
 [34 53]]


In [138]:
# create a filter which will be boolean values for whether each element meets this condition

filter=(an_array>25)
print(filter)

[[False False]
 [ True  True]
 [ True  True]]


In [139]:
# we can now select just those elements which meet that criteria
print(an_array[filter])

[34 53 34 53]


In [140]:
# For short, we could have just used the approach below without the need for the separate filter array.
an_array[an_array>15]

array([22, 23, 34, 53, 34, 53])

What is particularly useful is that we can actually change elements in the array applying a similar logical filter. Let's add 100 to all the even values.

In [141]:
an_array[an_array%2==0]+=100
print(an_array)

[[122  23]
 [134  53]
 [134  53]]


# Datatypes and Array Operations



In [142]:
ex1=np.array([11,12])  # python assingning data type
print(ex1.dtype)

int32


In [143]:
ex2=np.array([11.0,11.33,55.4])
print(ex2.dtype)

float64


In [144]:
ex3=np.array([11,21] , dtype=float)    # you can also tell the python datatype
print(ex3)

[11. 21.]


you can use this to force floats into integers (using floor function)


In [145]:
ex4 = np.array([11.1,12.7], dtype=np.int64)
print(ex4.dtype)
print()
print(ex4)

int64

[11 12]



# arithmatic array operation


In [146]:
import numpy as np
x = np.array([[111,112],[121,122]], dtype=np.int)
y = np.array([[211.1,212.1],[221.1,222.1]], dtype=np.float64)

print(x)
print()
print(y)

[[111 112]
 [121 122]]

[[211.1 212.1]
 [221.1 222.1]]


C:\Users\chetan\AppData\Local\Temp\ipykernel_9960\2364180563.py:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array([[111,112],[121,122]], dtype=np.int)


In [147]:
#add
print(x+y)
print()
print(np.add(x,y))

[[322.1 324.1]
 [342.1 344.1]]

[[322.1 324.1]
 [342.1 344.1]]


In [148]:
# multiply
print(x * y)
print()
print(np.multiply(x, y))

[[23432.1 23755.2]
 [26753.1 27096.2]]

[[23432.1 23755.2]
 [26753.1 27096.2]]


In [149]:
# substract
print(x-y)
print()
print(np.subtract(x, y))

[[-100.1 -100.1]
 [-100.1 -100.1]]

[[-100.1 -100.1]
 [-100.1 -100.1]]


In [150]:
    #divid
print(x/y)
print()
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]

[[0.52581715 0.52805281]
 [0.54726368 0.54930212]]


In [151]:
#squre root
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [152]:
#exponennt
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


# statastic method sorting and set operations



Set operations

In [153]:
#Setup random 2x5 matrix
arr = 10 * np.random.randn(2,5) #random.random or random.randn or random.randint
print(arr)

[[ 5.80393412  3.10471647 -7.04317702 -0.39533532 11.17394718]
 [-8.4722944  -7.1396758  -3.34617324  9.08279551  9.24342351]]


In [154]:
arr.mean()  #compute the mean for all element

1.2012161005912965

In [155]:
arr.mean(axis=1)  # compute the mean by row

array([ 2.52881709, -0.12638489])

In [156]:
arr.mean(axis=0)    #compute the mean by column

array([-1.33418014, -2.01747967, -5.19467513,  4.3437301 , 10.20868535])

In [157]:
# sum all the element 
arr.sum()

12.012161005912965

In [158]:
#compute the meadian
print(np.median(arr,axis=1))

[ 3.10471647 -3.34617324]


# sorting

In [159]:
# create a 10 element array
unsorted=np.random.randn(10)
print(unsorted)

[-1.28320692 -1.34634383  0.56413413 -0.61914162 -0.63422293  0.57620491
 -1.02617972  0.01925567  0.3722971   0.72921856]


In [160]:
sorted=np.array(unsorted)
sorted.sort()
print(sorted)

[-1.34634383 -1.28320692 -1.02617972 -0.63422293 -0.61914162  0.01925567
  0.3722971   0.56413413  0.57620491  0.72921856]


In [161]:
unsorted.sort()
print(unsorted)

[-1.34634383 -1.28320692 -1.02617972 -0.63422293 -0.61914162  0.01925567
  0.3722971   0.56413413  0.57620491  0.72921856]


In [162]:
# finding unique element

In [163]:
import numpy as np
arrn=np.array([1,1,1,2,234,5,6,64,4,3,3,3,5])
print(np.unique(arrn))    # it will return unique value

[  1   2   3   4   5   6  64 234]




# Set Operations with np.array data type:



In [164]:
s1 = np.array(['desk','chair','bulb'])
s2 = np.array(['lamp','bulb','chair'])
print(s1, s2)

['desk' 'chair' 'bulb'] ['lamp' 'bulb' 'chair']


In [165]:
print(np.intersect1d(s1,s2))   #commmon values between s1 and s2

['bulb' 'chair']


In [166]:
print(np.union1d(s1,s2))   # uncommon values of elements

['bulb' 'chair' 'desk' 'lamp']


In [167]:
print(np.setdiff1d(s1,s2))  #elements in s1 that are not in s2

['desk']


In [168]:
print(np.in1d(s1,s2))   #Which element of s1 are in s2

[False  True  True]






# Broadcasting:

In [169]:
import numpy as np
start=np.zeros((4,3))
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [170]:
# create rank 1 array with 3 value

add_row=np.array(([1,2,4]))

In [171]:
add_row

array([1, 2, 4])

In [172]:
y=start+add_row
print(y)

[[1. 2. 4.]
 [1. 2. 4.]
 [1. 2. 4.]
 [1. 2. 4.]]


In [173]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols=np.array([[0,1,2,3]])
print(add_cols)
print()
print(add_cols.T)

[[0 1 2 3]]

[[0]
 [1]
 [2]
 [3]]


In [174]:
# this will just broadcast in both dimensions
add_scalar = np.array([1])  
print(start+add_scalar)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [175]:
#Create 3x4 array

arrA=np.array([[12,23,4,55],[43,5,55,44],[54,64,32,22]])
print(arrA)

[[12 23  4 55]
 [43  5 55 44]
 [54 64 32 22]]


In [176]:
# create 4x1 array
arrB = [0,1,0,2]
print(arrB)
      

[0, 1, 0, 2]


In [177]:
# add the two together by broadcasting
print(arrA + arrB)


[[12 24  4 57]
 [43  6 55 46]
 [54 65 32 24]]


# sum

In [178]:
ex1 = np.array([[11,12],[21,22]])

print(np.sum(ex1))      

66


In [179]:
print(np.sum(ex1, axis=0))  # columnwise sum


[32 34]


In [180]:
print(np.sum(ex1, axis=1))  # rowwise sum


[23 43]


# Element-wise Functions:



For example, let's compare two arrays values to get the maximum of each.

In [181]:
# random array
x = np.random.randn(8)
x

array([ 0.83759709,  1.49916071, -0.35499053, -1.95039156, -0.17290928,
       -0.33876894,  0.10706   ,  1.20277806])

In [182]:
# another random array
y = np.random.randn(8)
y

array([-0.12603476, -0.44210039, -0.45067446,  1.75680075,  0.34835211,
       -0.14825101,  0.25258758,  0.59677761])

In [183]:
# returns element wise maximum between two arrays
import numpy as np
x = np.random.randn(2,3)
y = np.random.randn(2,3)
np.maximum(x, y)

array([[ 1.25579354,  0.88283161,  1.27156539],
       [ 1.05628046, -0.01780662,  0.07860355]])

# Reshaping array:

In [184]:
# grab values from 0 through 19 in an array
arr = np.arange(20)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [185]:
arr.reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [186]:
arr.T

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [187]:
# indexing using where

x1=np.array([1,2,3,4,5])
y1=np.array([11,22,33,44,55])
filter=np.array([True, False,True,False,True])
# where we have true in filter it will print x_1 value and for false y_1 value
# this is the working of .where function
print(np.where(filter,x1,y1))

[ 1 22  3 44  5]


In [188]:
mat=np.random.rand(5,5)

In [189]:
mat


array([[0.38896586, 0.4942177 , 0.86233044, 0.86661716, 0.39501338],
       [0.3429719 , 0.54900534, 0.0276192 , 0.21925722, 0.14961198],
       [0.8047594 , 0.64149139, 0.67985852, 0.01791659, 0.23550595],
       [0.74931497, 0.84979934, 0.02150138, 0.69107337, 0.69166507],
       [0.39903184, 0.60191385, 0.2072713 , 0.52176751, 0.62843277]])

In [190]:
print(np.where(mat>0.5,1000, -1))

[[  -1   -1 1000 1000   -1]
 [  -1 1000   -1   -1   -1]
 [1000 1000 1000   -1   -1]
 [1000 1000   -1 1000 1000]
 [  -1 1000   -1 1000 1000]]


In [191]:
'''
iF mat>0.5 
replace 1000
else:
replace -1

'''

'\niF mat>0.5 \nreplace 1000\nelse:\nreplace -1\n\n'

# any and all conditions

In [192]:
arr_bull=np.array([True, True, False, False])
arr_bull.any()

True

In [193]:
# returns true if any value true

In [194]:
arr_bull.all() # are all values True


False


# Merging data sets:

In [195]:
k=np.random.randint(low=2, high=50,size=(2,2))
print(k)

print()
M = np.random.randint(low=2,high=50,size=(2,2))
print(M)

[[37  6]
 [18 20]]

[[21 21]
 [38 23]]


In [196]:
np.vstack((k,M))  # join vertically

array([[37,  6],
       [18, 20],
       [21, 21],
       [38, 23]])

In [197]:
np.hstack((k,M)) # join horizontally

array([[37,  6, 21, 21],
       [18, 20, 38, 23]])

In [198]:
np.concatenate([k,M], axis=0)

array([[37,  6],
       [18, 20],
       [21, 21],
       [38, 23]])

In [199]:
np.concatenate([k,M], axis=1)

array([[37,  6, 21, 21],
       [18, 20, 38, 23]])

In [200]:
# dot product of matrics and inner product of vectors: 

x2d=np.array([[1,1],[1,1]])
y2d=np.array([[2,2],[2,2]])

print(x2d)
print()
print(y2d)
print(x2d.dot(y2d))
#or
print(np.dot(x2d,y2d))

[[1 1]
 [1 1]]

[[2 2]
 [2 2]]
[[4 4]
 [4 4]]
[[4 4]
 [4 4]]


In [201]:
# determine inner product of two vector

x=np.array([1,1])
y=np.array([5,5])
print(np.dot(x,y))

print()
print(x.dot(y))


10

10


# sum

In [247]:
ex1=np.array([[11,22],[23,54]])
print(np.sum(ex1))  # add all element

110


In [251]:
print(np.sum(ex1, axis=1)) # colum wise 

[33 77]


In [252]:
print(np.sum(ex1, axis=0)) #Row wise

[34 76]


# element wise function

In [214]:
x=np.random.randn(8)
x

array([ 1.10884229, -0.24731538, -1.45469036,  0.66867274,  0.50890176,
        0.92109032, -1.49069895,  2.09258319])

In [215]:
# another random array

y=np.random.randn(8)
y

array([-0.16413986,  0.20308779, -0.80601822, -0.67025353, -0.14269572,
        0.80612231, -1.61188655,  0.20479575])

In [216]:
import numpy as np
x=np.random.randn(2,3)
y=np.random.randn(2,3)
np.maximum(x,y)

array([[1.99061881, 1.41719831, 0.54707156],
       [1.93717965, 1.58551732, 0.6273417 ]])

In [217]:
# reshaping an array


In [218]:
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [219]:
arr.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Transpose

In [220]:
arr1=np.array([[12,32],[23,44]])
arr1.T

array([[12, 23],
       [32, 44]])

# indexing using where ()

In [221]:
x1=np.array([1,2,3,4,5,5,6])
y1=np.array([9,7,5,4,3,3,3])
filter=np.array([True, False,True,True,False,False,True])
# wherer we have true in filter it will print x1 for false it will print y1
#this is working of filter

In [222]:
out=np.where(filter,x1,y1)
print(out)

[1 7 3 4 3 3 6]


In [223]:
mat=np.random.rand(5,5)

In [224]:
mat

array([[0.96450548, 0.15795463, 0.41702716, 0.70877364, 0.05930341],
       [0.19043076, 0.79181724, 0.8292468 , 0.05599694, 0.07477867],
       [0.22422185, 0.0775311 , 0.52265255, 0.77915356, 0.62367029],
       [0.00814772, 0.74578614, 0.39738082, 0.13808803, 0.13547509],
       [0.22942989, 0.94794316, 0.36439777, 0.52279233, 0.38878376]])

In [225]:
np.where(mat >0.5, 1000, -2)

array([[1000,   -2,   -2, 1000,   -2],
       [  -2, 1000, 1000,   -2,   -2],
       [  -2,   -2, 1000, 1000, 1000],
       [  -2, 1000,   -2,   -2,   -2],
       [  -2, 1000,   -2, 1000,   -2]])

In [226]:
'''

if mat> 0.5 replace it with 1000 
else
replace it with -2
'''

'\n\nif mat> 0.5 replace it with 1000 \nelse\nreplace it with -2\n'

In [227]:
# any and all condition

arr_bools=np.array([True, False, True])
arr_bools.any()  # any function returns true if any value is true

True

In [228]:
# all condition

arr_bools.all()  # returns true if all valuse are true

False

# Random no generation

In [229]:
a=np.random.randint(low=2, high=50,size=5)
print(a)

[23 31 10 39 29]


In [230]:
np.random.permutation(a)   # returns ordering of element in a

array([23, 31, 10, 39, 29])

In [231]:
np.random.uniform(size=4)   # uniform distribution

array([0.55583238, 0.60791059, 0.36382358, 0.20721966])

In [232]:
y=np.random.normal(size=(1,5))

In [233]:
y

array([[-0.23042277,  0.12603173,  0.48003437, -0.63642144,  0.72061825]])

# merging data sets

In [234]:
a=np.random.randint(low=2, high=39,size=(2,2))
a



array([[12, 33],
       [37, 26]])

In [235]:
b=np.random.randint(low=2, high=39,size=(2,2))
b

array([[20, 24],
       [ 5, 23]])

In [236]:
np.hstack((a,b))

array([[12, 33, 20, 24],
       [37, 26,  5, 23]])

In [237]:
np.vstack((a,b))

array([[12, 33],
       [37, 26],
       [20, 24],
       [ 5, 23]])

In [238]:
np.concatenate([a,b], axis=1)    #row wise

array([[12, 33, 20, 24],
       [37, 26,  5, 23]])

In [239]:
# np.concatenate([a,b], axis=0)   colum wise